### ISSUE TITLE
Add to Bower

### ISSUE THREAD

**Issue by manuelmeurer** [thdoan/scalem#1]
Could you make Scalem a Bower package?
http://bower.io/#defining-a-package

**Comment by thdoan** [comment]
You can now install through npm by typing `npm install scalem`.

**Comment by manuelmeurer** [comment]
I think it would make sense to make it a Bower package as well, not just npm: http://bower.io/docs/creating-packages/
This would make it usable via https://rails-assets.org/ as well.

**Comment by thdoan** [comment]
OK, let me look into Bower since I haven't used it myself.

**Comment by manuelmeurer** [comment]
:+1:

**Comment by thdoan** [comment]
You can now `bower install scalem` :-)

**Comment by manuelmeurer** [comment]
Sweet!
