### ISSUE TITLE
Is it bug? I think...

### ISSUE THREAD

**Issue by YusufAkyol** [thdoan/scalem#2]
Hi,
I congratulate you for that work and share it with us-developers. 
I think there is a scale problem.
Best regards.
![bug](https://cloud.githubusercontent.com/assets/4185252/5670064/5c6745bc-9785-11e4-99ef-947b638f6fb8.jpg)

**Comment by thdoan** [comment]
Hi, can you explain what exactly is the problem?

**Comment by YusufAkyol** [comment]
Hi,
"Responsive Heading" must be single line. Isn't it?
But sometimes header is breaked into two line.
Is there a solution for it?
Best regards.

**Comment by thdoan** [comment]
Thanks for reporting this. This has been fixed as of v1.0.3.
